#pragma once

#include "NativeGameplayTags.h"

namespace ALSXTOverlayModeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuildingPlan)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flashlight)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeOneHanded)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeTwoHanded)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pickaxe)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knife)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hammer)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sword)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Katana)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grenade)
}

namespace ALSXTLocomotionActionTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallJumping)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRunning)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unarmed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeWeapon)
}

namespace ALSXTSexTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Male)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Female)
}

namespace ALSXTLocomotionVariantTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style01)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style02)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style03)
}

namespace ALSXTInjuryTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Head)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abdomen)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftArm)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RightArm)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftLeg)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RightLeg)
}

namespace ALSXTCombatStanceTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutral)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ready)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Focused)
}

namespace ALSXTWeaponFirearmStanceTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Regular)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CantedLeft)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CantedRight)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Underbarrel)
}

namespace ALSXTWeaponReadyPositionTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Carry)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PatrolReady)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LowReady)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HighReady)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AroundCover)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Retention)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hip)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ready)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hidden)
}