#pragma once

#include "NativeGameplayTags.h"

namespace ALSXTWeaponFirearmCantTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FortyFive)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ninety)
}

namespace AlsxtFirearmFireModeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SemiAuto)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burst)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Automatic)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InterruptibleBurst)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlamFire)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gatling)
}

namespace AlsxtFirearmTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grenade)
}

namespace AlsxtReloadingTypeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Drop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Retention)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tactical)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DropAimed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RetentionAimed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TacticalAimed)
}

namespace AlsxtFirearmFingerPoseTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OutsideGuard)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OnTrigger)
}

namespace AlsxtFirearmFingerActionTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineRelease)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SafetyOn)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SafetyOff)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SelectUp)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SelectDown)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PullingTrigger)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TogglingAccessory1)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TogglingAccessory2)
}

namespace AlsxtFirearmSightLocationTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ironsights)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReceiverTop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelTop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelLeft)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelRight)
}