#pragma once

#include "NativeGameplayTags.h"

namespace ALSXTOverlayModeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuildingPlan)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flashlight)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeOneHanded)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeTwoHanded)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pickaxe)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Knife)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hammer)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sword)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Katana)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grenade)
}

namespace ALSXTLocomotionActionTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallJumping)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRunning)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unarmed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeWeapon)
}

namespace ALSXTSexTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Male)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Female)
}