#pragma once

#include "NativeGameplayTags.h"

namespace ALSXTFirearmFireModeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SemiAuto)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burst)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Automatic)
}

namespace ALSXTFirearmTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grenade)
}

namespace ALSXTReloadingTypeTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Drop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Retention)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tactical)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DropAimed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RetentionAimed)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TacticalAimed)
}

namespace ALSXTFirearmFingerPoseTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OutsideGuard)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OnTrigger)
}

namespace ALSXTFirearmFingerActionTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineRelease)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SafetyOn)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SafetyOff)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SelectUp)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SelectDown)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PullingTrigger)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TogglingAccessory1)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TogglingAccessory2)
}

namespace ALSXTFirearmSightLocationTags
{
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ironsights)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReceiverTop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelTop)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelLeft)
	ALSXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BarrelRight)
}