#pragma once

#include "NativeGameplayTags.h"

namespace AlsxtExtrasBlockPresetTags
{
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dark)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Obstacle)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ObstacleDark)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NeonPink)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NeonGreen)
	ALSXTEXTRAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Custom)
}
